<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-user-assign-privilege'),
    'breadcrumbs' => ['admin-user']
]);
$privilege = config()->get('privilege')->all();
$flipped_privilege = array_flip($privilege);
$privilege_txt = isset($flipped_privilege[$this->user->privilege]) ? $flipped_privilege[$this->user->privilege] : $this->user->privilege;

?>

<?php $this->section('page-body'); ?>

<div class="row column">
    <p>
        Assign privilege to this user.
    </p>
    <p>
        <span><?php echo $this->user->nick; ?></span>,
        <span><?php echo $this->user->getPrimaryEmail(); ?></span>,
        <span><?php echo $privilege_txt; ?></span>
    </p>

    <?php if ($this->errors) { ?>
    <p>
        <ul class="menu vertical">
            <?php foreach ($this->errors as $key => $val) { ?>
                <li><span class="label alert"><?php echo $key; ?>, <?php echo trans($val); ?></span></li>
            <?php } ?>
        </ul>
    </p>
    <?php } ?>

    <form action="" method="post">
        <?php echo csrf_field(); ?>

        <input type="hidden" name="uid" value="<?php echo $this->user->uid; ?>">

        <div>
            <select name="privilege">
                <option value=""> - select one - </option>
                <option value="0"> normal </option>
                <?php foreach ($privilege as $key => $val) { ?>
                    <option value="<?php echo $val; ?>"><?php echo $key; ?></option>
                <?php } ?>
            </select>
        </div>

        <div>
            <input type="submit" class="button tiny" value="<?php echo trans('submit'); ?>">
            <a href="<?php echo route_url('admin-user'); ?>"><?php echo trans('cancel'); ?></a>
        </div>
    </form>

</div>

<?php $this->replace(); ?>
