<?php

    $this->layout('layout/ipar', [
        'header_menu' => 'ipar-article-index',
        'tdk_keywords' => true,
        'tdk_description' => true,
    ]);
?>

<?php $this->section('main'); ?>
<div class="article-set-wrap"></div>

<div class="loading" data-action="article" data-page="1">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <?php echo trans('no-more'); ?>
    </div>
</div>
<?php $this->replace(); ?>

<?php $this->section('side'); ?>
    <?php echo $this->insert('module/sidebar/section-rqt'); ?>
    <?php echo $this->insert('module/sidebar/section-product'); ?>
<?php $this->replace(); ?>
