<?php
$type = ($this->group) ? 'group' : 'company';
?>
<form action="<?php echo $this->action; ?>" method="post" enctype="multipart/form-data">
    <?php echo csrf_field(); ?>
    <input type="hidden" name="uid" value="<?php echo current_uid(); ?>">
    <input type="hidden" name="gid" value="<?php echo $this->{$type}->gid; ?>">
    <p><?php echo trans('Are-you-sure-to-activate-this-company?') ?></p>
    <h2><?php echo $this->{$type}->fullname; ?></h2>


    <?php if ($this->errors) { ?>
        <p class="errors">
            <?php foreach ($this->errors as $err_key => $err_val) { ?>
                <span class="label alert">
                    <?php echo trans($err_key); ?>,
                    <?php echo trans($err_val); ?>
                </span>
            <?php } ?>
        </p>
    <?php } ?>
    <br>
    <div>
        <input type="submit" class="button small" value="<?php echo trans('sure'); ?>">
        <a href="javascript:history.back(-1)" class="button success small"><?php echo trans('return'); ?></a>
    </div>
</form>