<?php
$range_config = config()->get('size_range');
$type_key = get_type_key($this->group->type_id);
?>
<div class="group-info">
    <div class="logo-box">
        <ul>
            <li class="group-logo">
                <span class="button <?php if ($this->group->status == 1) echo 'success'; ?>"><?php echo get_type_key($this->group->type_id) ?></span>
            </li>
            <li class="group-fullname"><span><?php echo $this->group->fullname; ?></span></li>
            <li class="group-operation">
                <?php if ($this->group->status == 1) { ?>
                    <a href="<?php echo route_url("admin-ui-{$type_key}-deactivate", ['gid' => $this->group->gid]) ?>">
                        <?php echo trans('deactivate') ?>
                    </a>
                <?php } else { ?>
                    <a href="<?php echo route_url("admin-ui-{$type_key}-activate", ['gid' => $this->group->gid]) ?>">
                        <?php echo trans('activate') ?>
                    </a>
                <?php } ?>
                <a href="<?php echo route_url("admin-ui-{$type_key}-edit", ['gid' => $this->group->gid]); ?>"
                   target="_blank">
                    <?php echo trans('edit'); ?>
                </a>
                <?php if ($this->group->status == 0) {
                    echo '<a href="' . route_url("admin-ui-{$type_key}-delete", ['gid' => $this->group->gid]) . '">' . trans('delete') . '</a>';
                } ?>
            </li>
        </ul>
    </div>
    <p class="group-time-info">
        <span class="group-create-info">
            Created: <span class="group-created-person"><?php echo user($this->group->uid)->nick; ?></span>
            <span class="group-created"><?php echo $this->group->created; ?></span>
        </span>
        <span class="group-changed-info">
            Last edit: <span class="group-changed-person"><?php echo user($this->group->uid)->nick; ?></span>
            <span class="group-changed"><?php echo $this->group->changed; ?></span>
        </span>
    </p>
    <div class="group-content-box">
        <div class="group-logo">
            <img src="<?php
            if (json_decode($this->group->logo, true)) {
                echo img_src($this->group->getLogo(), 'small');
            } else {
                echo static_url('/img/default_img.png');
            }
            ?>">
            <a href="<?php echo route_url("admin-ui-{$type_key}-logo", ['gid' => $this->group->gid]); ?>"
               class="change-logo">
                <i class="icon icon-camera"></i>
            </a>
        </div>
        <div class="group-description">
            <p>
                <span><?php echo trans("name") ?>：</span>
                <?php echo $this->group->name; ?>
            </p>
            <p>
                <span><?php echo trans("establish Time") ?>：</span>
                <?php echo $this->group->established; ?>
            </p>
            <p>
                <span><?php echo trans("website") ?>：</span>
                <a href="<?php echo $this->group->website; ?>" target="_blank">
                    <?php echo $this->group->website; ?>
                </a>
            </p>
            <p>
                <span><?php echo trans("size") ?>：</span>
                <?php echo array_search($this->group->size_range_id, $range_config->all()); ?>
            </p>
        </div>
    </div>
</div>
