<?php
$social_config = config()->get('social');
$type = ((bool)$this->group) ? "group" : "company";
?>
<div class="row column">
    <h1><?php echo trans("admin-ui-{$type}-social-delete"); ?></h1>
    <br>
    <p><?php echo trans('Are-you-sure-to-delete-this-social?') ?></p>
    <table>
        <thead>
        <tr>
            <th class="social"><?php echo trans("social") ?></th>
            <th class="name"><?php echo trans("name") ?></th>
            <th class="url"><?php echo trans("url") ?></th>
            <th class="qr-code"><?php echo trans("qrcode") ?></th>
        </tr>
        </thead>
        <tbody>

        <tr>
            <td class="social">
                <?php echo array_search($this->group_social->social_id, $social_config->all());
                ?>
            </td>
            <td class="name"><?php echo $this->group_social->name; ?></td>
            <td class="url">
                <?php echo $this->group_social->url; ?>
            </td>
            <td class="qr-code">
                <?php echo $this->group_social->qrcode; ?>
            </td>
        </tr>
        </tbody>
    </table>
    <form action="<?php echo $this->action; ?>" method="post" enctype="multipart/form-data">
        <?php echo csrf_field(); ?>
        <input type="hidden" name="id" value="<?php echo $this->group_social->id; ?>">
        <input type="hidden" name="gid" value="<?php echo $this->{$type}->gid; ?>">
        <br>
        <div>
            <input type="submit" class="button small" value="<?php echo trans('sure'); ?>">
            <a class="button success small" href="<?php echo route_url("admin-ui-{$type}_social-list", ['gid'
            => $this->{$type}->gid]); ?>">
                <?php echo trans('return'); ?>
            </a>
        </div>
    </form>
</div>