<div class="row column">
    <form action="<?php echo $this->action; ?>" method="post" enctype="multipart/form-data">
        <?php echo csrf_field(); ?>
        <input type="hidden" name="uid" value="<?php echo current_uid(); ?>">
        <input type="hidden" name="gid" value="<?php echo $this->company->gid; ?>">
        <table>
            <tbody>
            <tr class="type">
                <th><?php echo trans('type') . "*"; ?></th>
                <td>
                    <select name="type_id">
                        <option value="">ALL</option>
                        <option value="14"><?php echo trans('group'); ?></option>
                        <option value="15" selected><?php echo trans('company'); ?></option>
                    </select>
                </td>
            </tr>
            <tr>
                <th><?php echo trans('name') . "*"; ?></th>
                <td><input type="text" name="name" value="<?php echo $this->company->name; ?>"></td>
            </tr>
            <tr>
                <th><?php echo trans('fullname') . "*"; ?></th>
                <td><input type="text" name="fullname" required="required" value="<?php echo $this->company->fullname;
                    ?>"></td>
            </tr>
            <tr>
                <th><?php echo trans('legal-person'); ?></th>
                <td>
                    <input type="text" name="legal_person"
                           value="<?php echo $this->company->legal_person; ?>">
                </td>
            </tr>
            <tr>
                <th><?php echo trans('email'); ?></th>
                <td>
                    <input type="email" name="email" value="<?php echo $this->company->email; ?>">
                </td>
            </tr>
            <tr>
                <th><?php echo trans('register-date'); ?></th>
                <td>
                    <input type="datetime-local" name="established"
                           value="<?php echo substr($this->company->established, 0, 10) . 'T' . substr($this->company->established, 11); ?>">
                </td>
            </tr>
            <tr>
                <th><?php echo trans('register-address'); ?></th>
                <td>
                    <input type="text" name="reg_address"
                           value="<?php echo $this->company->reg_address; ?>">
                </td>
            </tr>
            <tr>
                <th><?php echo trans('company-address'); ?></th>
                <td>
                    <input type="text" name="company_address"
                           value="<?php echo $this->company->company_address; ?>">
                </td>
            </tr>
            <tr>
                <th><?php echo trans('size'); ?></th>
                <td>
                    <select name="size_range_id">
                        <option value="">-</option>
                        <?php
                        foreach (config()->get('size_range')->all() as $key => $id) {
                            echo '<option ';
                            if ($id == $this->company->size_range_id) {
                                echo ' selected ';
                            }
                            echo 'value ="' . $id . '" >';
                            echo $key;
                            echo '</option>';
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr class="content">
                <th><?php echo trans('content'); ?><br/><span>(<?php echo trans('1000-words-or-less'); ?>)</span></th>
                <td>
                    <textarea name="content"><?php echo $this->company->content; ?></textarea>
                </td>
            </tr>
            <tr>
                <th><?php echo trans('website'); ?></th>
                <td><input type="url" name="website" value="<?php echo $this->company->website; ?>"
                           placeholder="<?php echo trans('http://website-address'); ?>"></td>
            </tr>
            </tbody>
        </table>

        <?php if ($this->errors) { ?>
            <p class="errors">
                <?php foreach ($this->errors as $err_key => $err_val) { ?>
                    <span class="label alert"><?php echo trans($err_key); ?>, <?php echo trans($err_val); ?></span>
                <?php } ?>
            </p>
        <?php } ?>
        <br>
        <div>
            <input type="submit" class="button small" value="<?php echo trans('sure'); ?>">
            <a class="button success small" href="<?php
            if ($this->action == 'add') {
                echo route_url('admin-ui-group-index');
            } else {
                echo route_url('admin-ui-company-show', ['gid' => $this->company->gid]);
            }
            ?>">
                <?php echo trans('return'); ?>
            </a>
        </div>
    </form>

</div>