<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-idea-show'),
    'breadcrumbs' => ['admin-entity', 'admin-idea'],
]);
if ($page = http_request()->query->get('page')) {
    $is_info = false;
    $is_abbr = false;
} else {
    $is_info = true;
    $is_abbr = true;
}
?>

<?php $this->section('page-body'); ?>
<div class="entity-show idea-show">

    <?php echo $this->insert('module/entity-show-top', [
        'entity' => $this->idea,
        'is_info' => $is_info,
        'is_abbr' => $is_abbr,
    ]); ?>

    <div class="idea-story-set">
        <?php echo $this->insert('module/story-set', ['story-set' => $this->story_set]); ?>
    </div>
</div>
<?php $this->replace(); ?>

