<?php
$this->layout('layout/ipar', [
    'html_title' => $this->user->nick,
]);
?>

<?php $this->section('main'); ?>

<?php echo $this->insert('module/i-home-top', ['user' => $this->user]); ?>

<?php echo $this->insert('module/i-home-menu', ['selected' => 'story']); ?>

<?php echo $this->insert('module/no-search-result') ?>

<div class="story-set-wrap"></div>

<div class="loading" data-action="story" data-page="1" data-uid="<?php echo $this->user->uid; ?>">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <?php echo trans('no-more'); ?>
    </div>
</div>

<?php $this->replace(); ?>

<?php $this->section('side'); ?>
<?php echo $this->insert('module/i-follow-right', [
    'uid' =>  $this->user->uid,
    'is_following' => $this->is_following ]); ?>
<?php $this->replace(); ?>
