<?php $this->layout('layout/admin', [
    'html_title' => trans('tag'),
    'breadcrumbs' => ['']
]); ?>

<?php $this->section('page-body'); ?>
<?php echo $this->insert('module/form/query',[
    'buttons'=>[
        ['link' => route_url('admin-ui-tag-add'), 'text' => trans('add-tag')]
    ]
]);?>
    <div class="row">
        <table class="groups">
            <thead>
            <tr>
                <th><?php echo trans('id'); ?></th>
                <th><?php echo trans('title'); ?></th>
                <th><?php echo trans('content'); ?></th>
                <th><?php echo trans('child_count'); ?></th>
                <th>编辑</th>
                <th>状态</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->tag_set->getItems() as $tag) { ?>
                <tr>
                    <td><?php echo $tag->id; ?></td>
                    <td class="tag-index-title">
                        <a href="<?php echo route_url('admin-ui-tag-show',['tag_id'=>$tag->id]);?>">
                        <?php echo $tag->title;?>
                        </a>
                    </td>
                    <td><?php echo $tag->content; ?></td>
                    <td><?php echo $tag->child_count; ?></td>
                    <td ><a href="<?php echo route_url('admin-ui-tag-edit', ['tag_id' => $tag->id]); ?>"><?php echo trans('edit'); ?></a></td>
                    <?php if ($tag->status==="1") { ?>
                        <td><a href="<?php echo route_url('admin-ui-tag-deactivate', ['tag_id' => $tag->id]);?>"><?php echo trans('deactivate');?></a></td>
                    <?php }  ?>
                    <?php if ($tag->status==="0") { ?>
                        <td><a href="<?php echo route_url('admin-ui-tag-activate', ['tag_id' => $tag->id]);?>"><?php echo trans('activate');?></a></td>
                    <?php }  ?>
                </tr>
            <?php } ?>

            </tbody>
        </table>

        <?php echo $this->insert('element/pagination', ['page_count' => $this->tag_set->getPageCount()]); ?>

    </div>

<?php $this->replace(); ?>