<?php $this->layout('layout/admin', [
    'html_title' => trans('tag'),
    'breadcrumbs' => ['']
]); ?>
<?php $tag = $this->tag; ?>
<?php $this->section('page-body'); ?>
    <div class="entity-show">
        <?php echo $this->insert("module/tag-menu", ['select' => 'content', 'tag' => $tag]); ?>
        <h2>标签：<?php echo $tag->title; ?></h2>
        <div class="tag-time">
            <ul>
                <li>Created: <?php echo $tag->created; ?></li>
                <li>Last edit: <?php echo $tag->changed; ?></li>
            </ul>
        </div>

        <div class="tag-body">
            <h3>标签内容</h3>
            <p>
                <?php echo $tag->content; ?>
            </p>
        </div>
    </div>


<?php $this->replace(); ?>