<?php if ($url = $this->activity_advice_banner_url) : ?>
    <style>
        #frame{
            position:relative;
            width:304px;
            height:274px;
            overflow:hidden;
            margin: 30px;
            margin-top: 0px;
            border-radius:5px
        }
        #photos img{
            float:left;
            width:304px;
            height:274px
        }
        #photos {
            position: absolute;
            z-index:9;
            width: calc(304px * 4);/*---修改图片数量的话需要修改下面的动画参数*/
        }
        .play{
            animation: ma 8s ease-out infinite alternate;
        }
        @keyframes ma {
            0%,25% {
                margin-left: 0px;
            }
            30%,50% {
                margin-left: -304px;
            }
            55%,75% {
                margin-left: -608px;
            }
            80%,100% {
                margin-left: -912px;
            }
        }
    </style>

    <div id="frame" >
        <div id="photos" class="play">
            <a href="<?php echo route_url('ipar-ui-page-activity_foundation') ?>">
                <img src="<?php echo static_url('/img/umbrella_ad.png') ?>" >
            </a>
            <a href="<?php echo route_url('ipar-ui-page-activity-index')?>">
                <img src="<?php echo json_decode($url); ?>" >
            </a>
            <a href="<?php echo route_url('ipar-ui-page-activity_foundation') ?>">
                <img src="<?php echo static_url('/img/umbrella_ad.png') ?>" >
            </a>
            <a href="<?php echo route_url('ipar-ui-page-activity-index')?>">
                <img src="<?php echo json_decode($url); ?>" >
            </a>
        </div>
    </div>
<?php endif; ?>
