<?php
$this->layout('layout/ipar');

$page_count = $this->entity_set->getPageCount();
$page = http_request()->query->get('page', $page_count);
$this->entity_set->setCurrentPage($page);
?>

<?php $this->section('main'); ?>

<?php echo $this->insert('module/entity-set', ['entity_set' => $this->entity_set]); ?>
<?php echo $this->insert('element/pagination-opposite', ['page_count' => $page_count, 'page' => $page]); ?>

<?php $this->replace(); ?>
