<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-product-add-pbranch'),
    'breadcrumbs' => ['admin-entity', 'admin-product'],
]);
?>

<?php $this->section('page-body'); ?>

    <?php echo $this->insert('module/entity-show-top', [
        'entity' => $this->product,
        'is_info' => false,
        'is_content' => false,
        'select' => 'pbranch',
    ]); ?>

    <div class="row column">
        <h2><?php echo trans('add-product-pbranch'); ?></h2>
        <?php echo $this->insert('module/form/admin-form-pbranch'); ?>
    </div>

<?php $this->replace(); ?>
