<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-product-add-solved'),
    'breadcrumbs' => ['admin-entity', 'admin-product'],
]);
?>

<?php $this->section('page-body'); ?>
<div class="entity-show">
    <?php echo $this->insert('module/entity-show-top', [
        'entity' => $this->product,
        'is_info' => false,
        'is_content' => false,
        'select' => 'solved',
    ]); ?>

    <div class="row column">
        <h2><?php echo trans('add-from-existing-solved'); ?></h2>
        <?php echo $this->insert('module/form/query'); ?>
        <?php echo $this->insert('module/form/select-exist', ['entity_set' => $this->rqt_set]); ?>
    </div>

    <div class="row column">
        <h2><?php echo trans('add-from-new-solved'); ?></h2>
        <?php echo $this->insert('module/form/admin-form-rqt'); ?>
    </div>

</div>

<?php $this->replace(); ?>
