<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-product-show'),
    'breadcrumbs' => ['admin-entity', 'admin-product'],
]);
?>
<?php $this->section('page-body'); ?>
<div class="entity-show">
    <?php echo $this->insert('module/entity-show-top', [
        'entity' => $this->product,
        'is_info' => false,
        'is_content' => false,
        'select' => 'property',
    ]); ?>

    <?php echo $this->insert('module/form/query', [
        'buttons' => [
            [
                'link' => route_url('admin-product-feature-add', ['eid' => $this->product->eid]),
                'text' => trans('add-feature')
            ],
            [
                'link' => route_url('admin-product-solved-add', ['eid' => $this->product->eid]),
                'text' => trans('add-solved')
            ],
            [
                'link' => route_url('admin-product-improving-add', ['eid' => $this->product->eid]),
                'text' => trans('add-improving')
            ],
        ]
    ]); ?>

    <?php echo $this->insert('module/entity-set', ['entity_set' => $this->property_set]); ?>
</div>


<?php $this->replace(); ?>
