<?php $this->layout('layout/admin', [
    'html_title' => trans('admin-ui-group-edit'),
    'breadcrumbs' => ['admin-ui-group-index']
]); ?>

<?php $this->section('page-body'); ?>
<div class="page-group-edit">
    <div class="row column">
        <h1><?php echo trans('admin-ui-group-edit'); ?></h1>
        <?php echo $this->insert('module/form/group/admin-form-group'); ?>
    </div>
</div>

<?php $this->replace(); ?>

