<div class="header-div article-header-div hide">
    <i class="icon icon-file"></i>
    <h3><?php echo trans('article'); ?></h3>
</div>
<div class="article-set-wrap"></div>
<div class="loading" data-action="search_article" data-page="1" data-query="<?php echo $this->query; ?>">
</div>

<div class="more-about article-hide hide">
    <a href="./search/article?query=<?php echo $this->query; ?>"><?php echo trans('see-more'); ?></a>
</div>
