<div class="header-div product-header-div hide">
    <i class="icon icon-product"></i>
    <h3><?php echo trans('product'); ?></h3>
</div>
<div class="product-set-wrap  search-product-div"></div>

<div class="loading" data-action="search_product" data-type_key="product" data-page="1"
     data-query="<?php echo $this->query; ?>">
</div>

<div class="more-about product-hide hide">
    <a href="./search/product?query=<?php echo $this->query; ?>"><?php echo trans('see-more'); ?></a>
</div>
