<div class="header-div rqt-header-div hide">
    <i class="icon icon-rqt-new-version"></i>
    <h3><?php echo trans('rqt'); ?></h3>
</div>
<div class="rqt-set-wrap"></div>

<div class="loading" data-action="search_rqt" data-page="1" data-type_key="rqt"
     data-query="<?php echo $this->query; ?>">
</div>

<div class="more-about rqt-hide hide">
    <a href="./search/rqt?query=<?php echo $this->query; ?>"><?php echo trans('see-more'); ?></a>
</div>
