<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-rqt-add-idea'),
    'breadcrumbs' => ['admin-entity', 'admin-rqt'],
]);
?>

<?php $this->section('page-body'); ?>
<div class="entity-show">
    <?php echo $this->insert('module/entity-show-top', [
        'entity' => $this->rqt,
        'is_info' => false,
        'is_content' => false,
        'select' => 'idea',
    ]); ?>


    <div class="row column">
        <h2><?php echo trans('add-idea'); ?></h2>
        <?php echo $this->insert('module/form/admin-form-idea'); ?>
    </div>
</div>


<?php $this->replace(); ?>
