<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-rqt-add-product'),
    'breadcrumbs' => ['admin-entity', 'admin-rqt'],
]);
?>

<?php $this->section('page-body'); ?>
<div class="entity-show">
    <?php echo $this->insert('module/entity-show-top', [
        'entity' => $this->rqt,
        'is_info' => false,
        'is_content' => false,
        'select' => 'product',
    ]); ?>

    <div class="row column">
        <h2><?php echo trans('add-solution-from-existed-product'); ?></h2>
        <?php echo $this->insert('module/form/query'); ?>
        <?php echo $this->insert('module/form/select-exist', ['entity_set' => $this->product_set]); ?>
    </div>

    <div class="row column">
        <h2><?php echo trans('add-solution-from-new-product'); ?></h2>
        <?php echo $this->insert('module/form/admin-form-product'); ?>
    </div>

</div>

<?php $this->replace(); ?>
