<?php $this->layout('layout/admin', [
    'html_title' => trans('admin-rqt'),
    'breadcrumbs' => ['admin-entity', 'admin-rqt']
]); ?>

<?php $this->section('page-body'); ?>

<?php echo $this->insert('module/form/query', [
    'buttons' => [
        ['link' => route_url('admin-rqt-add'), 'text' => trans('add-rqt')]
    ]
]); ?>


<div class="row column">
    <?php echo $this->insert('module/entity-set', ['entity_set' => $this->rqt_set]); ?>
</div>

<?php $this->replace(); ?>
