<?php
$type = ($this->group) ? 'group' : 'company';
?>
<form action="<?php echo $this->action; ?>" method="post">
    <?php echo csrf_field(); ?>
    <input type="hidden" name="id" value="<?php echo $this->group_office->id; ?>">
    <input type="hidden" name="gid" value="<?php echo $this->{$type}->gid; ?>">
    <label>
        <?php echo trans('name') . '*'; ?>
        <input type="text" name="name" required="required" value="<?php echo $this->group_office->name; ?>">
    </label>
    <label>
        <?php echo trans('address') . '*'; ?>
        <input type="text" name="office_address" required="required"
               value="<?php echo $this->group_office->office_address; ?>">
    </label>

    <?php if ($this->errors) { ?>
        <p class="errors">
            <?php foreach ($this->errors as $err_key => $err_val) { ?>
                <span class="label alert"><?php echo trans($err_key); ?>, <?php echo trans($err_val); ?></span>
            <?php } ?>
        </p>
    <?php } ?>
    <br>
    <div>
        <input type="submit" class="button small" value="<?php echo trans('sure'); ?>">
        <a class="button success small" href="<?php echo route_url("admin-ui-{$type}_office-list", ['gid'
        => $this->{$type}->gid]); ?>">
            <?php echo trans('return'); ?>
        </a>
    </div>
</form>

