<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-entity-deactivate')
]);
?>

<?php $this->section('page-body'); ?>

<div class="row column">
    <p>
        Are you sure to deactivate this group website?
    </p>

    <div>
        <h3><?php echo $this->group_website_set->title; ?></h3>
        <p><?php echo $this->group_website_set->url; ?></p>
    </div>

    <?php if ($this->errors) { ?>
    <p>
        <ul class="menu vertical">
            <?php foreach ($this->errors as $key => $val) { ?>
                <li><span class="label alert"><?php echo $key; ?>, <?php echo trans($val); ?></span></li>
            <?php } ?>
        </ul>
    </p>
    <?php } ?>

    <form action="" method="post">
        <?php echo csrf_field(); ?>
        <input type="hidden" name="id" value="<?php echo $this->group_website_set->id; ?>">
        <input type="hidden" name="gid" value="<?php echo $this->group_website_set->gid; ?>">
        <input type="hidden" name="last_url" value="<?php echo $this->last_url; ?>">
        <input type="submit" class="button tiny" value="<?php echo trans('yes'); ?>">
        <a onclick="history.go(-1)"><?php echo trans('cancel'); ?></a>
    </form>

</div>
<?php $this->replace(); ?>
