<?php $this->layout('layout/admin', [
    'html_title' => trans('admin-trans'),
    'breadcrumbs' => ['admin-trans'],
]); ?>

<?php $this->section('page-body'); ?>

<?php
if (!$query = $this->query) {
    $query = http_request()->query->get('query');
}
?>
<form class="admin-trans-query" method="get" action="<?php echo $this->action; ?>">
    <table>
        <tbody>
        <tr>
            <td>
                <input class="input-group-field" type="search" name="query" value="<?php echo $query; ?>">
            </td>
<?php /*
            <td width="166">
                <?php echo $this->insert('element/select-locale'); ?>
            </td>
 */ ?>
            <td width="60">
                <button class="button">search</button>
            </td>
            <td width="90">
                <a href="<?php echo route_url('admin-trans-add'); ?>" class="button success"><?php echo trans('add'); ?></a>
            </td>
        </tr>
        </tbody>
    </table>
</form>

<div class="row column">
    <?php echo $this->insert('module/table-trans', ['transes' => $this->transes,'user' =>$this->user]); ?>
</div>
<?php echo $this->insert('element/pagination', ['url' => 'admin-trans', 'opts' => [], 'page' => $this->page, 'page_count' => $this->page_count]); ?>
<?php $this->replace(); ?>
