<?php $this->layout('layout/invent', [
    'html_title' => $this->invent->title
]); ?>

<?php $this->section('invent-content'); ?>

    <div>
        <a href="<?php echo route_url('invent-appearance-create', ['zcode' => $this->invent->zcode]); ?>">
            <?php echo trans('create-appearance'); ?>
        </a>
    </div>

    <?php echo $this->insert('include/wrap-entities'); ?>

<?php /*
<?php foreach ($this->appearances as $appearance) { ?>
    <div class="invent-appearance">
        <a href="<?php echo route_url('invent-appearance-show', ['zcode' => $this->invent->zcode, 'eid' => $appearance->eid]); ?>">
            <?php echo $appearance->getTitle(); ?>
        </a>
    </div>
<?php } ?>
 */ ?>
<?php $this->replace(); ?>
