<?php $this->layout('layout/invent'); ?>

<?php $this->section('title'); ?>
    <?php echo trans('invent-feature-show'); ?>
<?php $this->append(); ?>

<?php $this->section('content'); ?>
    <div class="content">
        <?php echo $this->feature->content; ?>
    </div>
    <p>
        <a href="<?php echo route_url('invent-feature-edit', ['zcode' => $this->invent->zcode, 'eid' => $this->feature->eid]); ?>">Edit</a>
        <a href="<?php echo route_url('invent-feature-delete', ['zcode' => $this->invent->zcode, 'eid' => $this->feature->eid]); ?>">delete</a>
    </p>
<?php $this->replace(); ?>
