<?php $this->layout('layout/invent'); ?>

<?php $this->section('title'); ?>
    <?php echo trans('invent-rqt'); ?>
<?php $this->append(); ?>

<?php $this->section('content'); ?>
<?php foreach ($this->rqts as $rqt) { ?>
    <div class="invent-rqt">
        <a href="<?php echo route_url('invent-rqt-show', ['zcode' => $this->invent->zcode, 'eid' => $rqt->eid]); ?>">
            <?php echo $rqt->getTitle(); ?>
        </a>
    </div>
<?php } ?>
<?php $this->replace(); ?>

