<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-entity-delete')
]);
?>

<?php $this->section('page-body'); ?>

<div class="row column">
    <p>
        Are you sure to delete this entity-<?php echo $this->entity->type;?>?
    </p>

    <?php if ($this->errors) { ?>
    <p>
        <ul class="menu vertical">
            <?php foreach ($this->errors as $key => $val) { ?>
                <li><span class="label alert"><?php echo $key; ?>, <?php echo trans($val); ?></span></li>
            <?php } ?>
        </ul>
    </p>
    <?php } ?>

    <form action="" method="post">
        <?php echo csrf_field(); ?>
        <input type="hidden" name="eid" value="<?php echo $this->entity->eid; ?>">
        <input type="hidden" name="type" value="<?php echo $this->entity->type; ?>">
        <input type="hidden" name="rqt_id" value="<?php echo $this->rqt->eid; ?>">
        <input type="submit" class="button tiny" value="<?php echo trans('yes'); ?>">
        <a onclick="history.go(-1)"><?php echo trans('cancel'); ?></a>
    </form>

</div>

<?php $this->replace(); ?>
