<?php
$this->layout('page', [
    'jses' => ['ipar.editor.js' => 1],
]);
?>


<?php $this->section('page-body'); ?>
    <?php echo $this->insert('include/form/story-form', [
        'story_title' => trans('page-rqt-create-title'),
        'action' => route_url('rqt-create-post'),
        'type' => 'rqt',
        'operatearea' => $this->insert('ipar/rqt/operatearea'),
        'cancel' => route_url('rqt-index')
    ]); ?>
<?php $this->replace(); ?>
