<?php $this->layout('layout/ipar', [
    'header_menu' => 'ipar-rqt-index',
    'tdk_keywords' => true,
    'tdk_description' => true,
]); ?>

<?php $this->section('cat');?>
<div class="rqt-page-banner" >
        <h1><?php echo trans('page-title-ipar-ui-rqt-index');?></h1>
        <p><?php echo trans('page-subtitle-ipar-ui-rqt-index');?></p>
</div>
<?php $this->append() ?>

<?php $this->section('main'); ?>
<div class="hot_tag_words">
    <div class="hot_tag_title">
        <span>
        <?php echo trans('hot_tag_title'); ?>
        </span>
    </div>
    <div class="hot_tag_content">
        <?php foreach ($this->hot_tag as $tag) : ?>
        <a href="<?php echo $tag['url']; ?>"><span><?php echo $tag['title']; ?></span></a>
        <?php endforeach; ?>
    </div>
</div>

<?php echo $this->insert('module/sort-toggle') ?>
<div class="story-set-wrap"></div>

<div class="loading" data-action="rqt" data-page="1" data-type_key="rqt">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <a href="<?php echo route_url('ipar-story-rqt'); ?>"><?php echo trans('explore-all-rqt-stories'); ?></a>
    </div>
</div>

<?php $this->append(); ?>

<?php $this->section('side'); ?>
    <?php echo $this->insert('module/temp_entrance_article') ?>
    <?php echo $this->insert('module/sidebar/section-product') ?>
    <?php echo $this->insert('module/sidebar/section-article') ?>
<?php $this->replace(); ?>
