<?php
$this->layout('layout/ipar', [
    'html_title' => $this->rqt->title,
    'header_menu' => 'ipar-rqt-index'
]);
?>

<?php $this->section('main'); ?>

<?php echo $this->insert('module/rqt-show-top', [
    'rqt' => $this->rqt,
    'tag_set' => $this->tag_set,
    'select' => 'product'
]); ?>


<div class="solution-set-wrap"></div>

<div class="loading" data-action="solution" data-stype_key="product" data-page="1" data-eid="<?php echo $this->rqt->eid; ?>">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <?php echo trans('no-more'); ?>
    </div>
</div>
<?php $this->replace(); ?>

<?php /* todo with story
<div class="story-set-wrap"></div>

<div class="loading" data-action="story" data-page="1" data-eid="<?php echo $this->rqt->eid; ?>">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <?php echo trans('no-more'); ?>
    </div>
</div>
<?php $this->replace(); ?>

<?php $this->section('side'); ?>
<?php echo $this->insert('module/follow-show-right', [
    'eid' =>  $this->rqt->eid,
    'followed' => $this->followed ]); ?>
<?php $this->replace(); ?>
 */ ?>

<?php $this->section('side'); ?>

<?php echo $this->insert('module/follow-show-right', [
    'eid' => $this->rqt->eid,
    'is_following' => $this->is_following
]); ?>

<?php echo $this->insert('module/side-share'); ?>

<?php $this->replace(); ?>
