<?php
$this->layout('layout/ipar', [
    'html_title' => $this->rqt->title,
    'header_menu' => 'ipar-rqt-index'
]);
?>

<?php $this->section('main'); ?>

<?php echo $this->insert('module/rqt-show-top', [
    'rqt' => $this->rqt,
    'select' => 'solution'
]); ?>

<div class="solution-set-wrap"></div>

<div class="loading" data-action="solution" data-page="1" data-eid="<?php echo $this->rqt->eid; ?>">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <?php echo trans('no-more'); ?>
    </div>
</div>
<?php $this->replace(); ?>
