<?php $this->layout('layout/ipar', [
    'header_menu' => 'ipar-rqt-index',
    'html_title' => $this->tag_main->title
]); ?>

<?php $this->section('main'); ?>

<h1><?php echo $this->tag_main->title; ?></h1>

<hr>

<div class="entity-set-wrap"></div>

<div class="loading" data-action="search" data-page="1" data-type="rqt" data-tag_id="<?php echo $this->tag_main->tag_id; ?>">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <a href="<?php echo route_url('ipar-story-rqt'); ?>"><?php echo trans('explore-all-rqt-stories'); ?></a>
    </div>
</div>

<?php $this->append(); ?>

<?php $this->section('side'); ?>
<?php echo $this->insert('module/rqt-sidebar') ?>
<?php $this->replace(); ?>
