<?php
$this->layout('layout/admin', [
    'html_title' => trans('admin-industry_tag-delete')
]);
?>

<?php $this->section('page-body'); ?>

    <div class="row column">
        <p>
            <?php echo trans("Are-you-sure-to-delete-this-industry-tag?"); ?>
        </p>

        <div>
            <h3><?php echo trans('title') . ":" . $this->industry_tag->title; ?></h3>
            <p><?php echo $this->industry_tag->content; ?></p>
        </div>

        <?php if ($this->errors) { ?>
            <p>
            <ul class="menu vertical">
                <?php foreach ($this->errors as $key => $val) { ?>
                    <li><span class="label alert"><?php echo $key; ?>, <?php echo trans($val); ?></span></li>
                <?php } ?>
            </ul>
            </p>
        <?php } ?>

        <form action="" method="post">
            <?php echo csrf_field(); ?>
            <input type="hidden" name="tag_id" value="<?php echo $this->industry_tag->tag_id; ?>">
            <input type="submit" class="button tiny" value="<?php echo trans('yes'); ?>">
            <a onclick="history.go(-1)"><?php echo trans('cancel'); ?></a>
        </form>
    </div>

<?php $this->replace(); ?>