<?php if($this->page_count > 1) {?>
    <ul class="pagination">
        <?php
$query = http_request()->query;
if (!$this->page) {
    $this->page = $query->get('page', 1);
}
$query_arr = $query->all();

$this->page = $this->page ? $this->page : 1;
$prev_page = ($this->page > 1) ? (int)($this->page - 1) : '1';
$next_page = ($this->page < $this->page_count) ? (int)($this->page + 1) : $this->page_count;
$next_page = $next_page > 0 ? $next_page : 1;
$firstShowPage = 1;
if($this->page_count > 5) {
    if($this->page > 4) {
        if ($this->page > ($this->page_count - 2)){
            $firstShowPage = $this->page_count - 4;
            $endShowPage = $this->page_count;
        } else {
            $firstShowPage = $this->page - 2;
        }
    }
    $endShowPage = $firstShowPage + 4;
} else {
    $endShowPage = $this->page_count;
}
$query_arr['page'] = 1;
$first_page_url = '?' . http_build_query($query_arr);
//$query_arr['page'] = $prev_page;
//$prev_page_url = '?' . http_build_query($query_arr);
//$query_arr['page'] = $next_page;
//$next_page_url = '?' . http_build_query($query_arr);
$query_arr['page'] = $this->page_count;
$end_page_url = '?' . http_build_query($query_arr);
        ?>
        <li class="pagination-previous"><a href="<?php echo $first_page_url; ?>"><?php echo trans('first-page'); ?></a></li>
        <?php /* <li class="pagination-previous"><a href="<?php echo $prev_page_url; ?>"><?php echo trans('prev-page'); ?></a></li> */ ?>
        <?php if($firstShowPage > 1) { echo '...'; }?>
        <?php for($i = $firstShowPage; $i <= $endShowPage; $i++){ ?>
<?php
$query_arr['page'] = $i;
$i_page_url = '?' . http_build_query($query_arr);
?>
        <?php if ($i == $this->page) { ?>
        <li class="current"><?php echo $i; ?></li>
        <?php } else { ?>
        <li><a href="<?php echo $i_page_url; ?>"><?php echo $i; ?></a></li>
        <?php } ?>
        <?php } ?>
        <?php if($endShowPage < $this->page_count) { echo '...'; }?>
        <?php /* <li class="pagination-next"><a href="<?php echo $next_page_url; ?>"><?php echo trans('next-page'); ?></a></li> */ ?>
        <li class="pagination-next"><a href="<?php echo $end_page_url; ?>"><?php echo trans('end-page'); ?></a></li>
    </ul>
<?php }?>
