<div class="home-banner">
    <div class="container">

        <div class="main-wrap">
            <div class="main">
                <h1 class="title"><?php echo trans('home-page-title'); ?></h1>
                <p class="subtitle"><?php echo trans('home-page-subtitle'); ?></p>
                <div class="button-wraps">
                    <a class="button" href="<?php echo route_url('mobile-reg'); ?>"><?php echo trans('join-ideapar'); ?></a>
                    <a class="button" href="<?php echo route_url('ipar-ui-page-about_us'); ?>"><?php echo trans('about-ideapar'); ?></a>
                </div>
            </div>
        </div>

        <div class="img-wrap">
            <div class="img">
                <img src="<?php echo static_url('/img/home-banner-center.png'); ?>">
            </div>
        </div>

    </div>
</div>

