#!/usr/bin/env php
<?php
$base_dir = realpath(__DIR__ . '/../');
$loader = require $base_dir . '/dev/vendor/autoload.php';

\Gap\Application::console([
    'base_dir' => $base_dir,
    'loader' => $loader
])->cmd($argv);

echo "\n";
