<?php $this->layout('layout/admin', [
    'breadcrumbs' => ['admin-ui-group-index']
]);
?>
<?php $this->section('page-body'); ?>
    <div class="page-company">
        <?php
        echo $this->insert('module/entity-menu-group', [
            'group' => $this->company,
            'select' => $this->select
        ]);
        ?>
        <?php echo $this->insert('module/form/company/admin-form-company_detail-show'); ?>
        <?php echo $this->insert('module/form/group_social/admin-form-group_social-show'); ?>
    </div>


<?php $this->replace(); ?>