<?php $this->layout('layout/invent', [
    'html_title' => $this->invent->title
]); ?>

<?php $this->section('invent-content'); ?>

    <div>
        <a href="<?php echo route_url('invent-sketch-create', ['zcode' => $this->invent->zcode]); ?>">
            <?php echo trans('create-sketch'); ?>
        </a>
    </div>

    <?php echo $this->insert('include/wrap-entities'); ?>

<?php /*
<?php foreach ($this->sketchs as $sketch) { ?>
    <div class="invent-sketch">
        <a href="<?php echo route_url('invent-sketch-show', ['zcode' => $this->invent->zcode, 'eid' => $sketch->eid]); ?>">
            <?php echo $sketch->getTitle(); ?>
        </a>
    </div>
<?php } ?>
 */ ?>
<?php $this->replace(); ?>
