<form action="<?php echo $this->action; ?>" method="post" enctype="multipart/form-data" class="user-setting-form">
    <?php echo csrf_field(); ?>
    <ul class="menu vertical">
        <li class="item">
            <div class="title"><?php echo trans('new-password'); ?></div>
            <?php echo $this->insert('module/form/user_setting/input-field', [
                'type' => 'password',
                'name' => 'password',
                'placeholder' => trans('enter-new-password'),
                'value' => '',
                'maxlength' => 21,
                'data_type' => '',
                'has_error' => isset($errors['password'])
            ]); ?>
            <i class="icon icon-eye-close view-password"></i>
        </li>
    </ul>

    <?php if ($this->errors) { ?>
        <p class="errors">
            <?php foreach ($this->errors as $err_key => $err_value) { ?>
                <span class="label alert">
                <?php echo $err_key; ?>,<?php echo trans($err_value); ?>
            </span>
            <?php } ?>
        </p>
    <?php } ?>
    
    <div>
        <input type="submit" class="button small" value="<?php echo trans('submit'); ?>">
        <a class="small"
           href="<?php echo route_url('ipar-ui-i-account-info', ['zcode' => $this->user->zcode]); ?>">
            <?php echo trans('back'); ?></a>
    </div>
</form>
