<?php
$this->layout('layout/ipar', [
    'html_title' => $this->query
]);
?>

<?php $this->section('main'); ?>

<div class="entity-set-wrap"></div>

<div class="loading" data-action="search" data-page="1" data-query="<?php echo $this->query; ?>">
    <div class="one">
        <a href="javascript:;" class="trigger"><?php echo trans('see-more'); ?></a>
    </div>
    <div class="two">
        <?php echo trans('no-more'); ?>
    </div>
</div>

<?php $this->replace(); ?>
