<form action="<?php echo $this->action; ?>" method="post">
    <?php echo csrf_field(); ?>
    <?php if ($this->eid) { ?>
    <input type="hidden" name="eid" value="<?php echo $this->eid; ?>">
    <input type="hidden" name="last_url" value="<?php echo $this->last_url; ?>">
    <?php } ?>
    <label>
        <?php echo trans( 'title'); ?>
        <input type="text" name="title" required="required" value="<?php echo $this->title; ?>">
    </label>
    <label>
        <?php echo trans( 'content'); ?>
        <?php echo $this->insert('element/zeditor', ['name' => 'content', 'value' => $this->content]); ?>
    </label>
    <?php $progress = config()->get('progress')->all();?><br>
    <label>
        <?php echo trans( 'progress'); ?>
        <select name="progress">
            <option value=""> - select one - </option>
            <?php
            foreach ($progress as $key => $val) { ?>
                <option value="<?php echo $key; ?>" <?php if($this->progress == $key) echo "selected = 'selected'";?>><?php echo $val; ?></option>
            <?php } ?>
        </select>
    </label>
    <?php if ($this->errors) { ?>
    <p class="errors">
        <?php foreach ($this->errors as $err_key => $err_val) { ?>
            <span class="label alert"><?php echo trans($err_key); ?>, <?php echo trans($err_val); ?></span>
        <?php } ?>
    </p>
    <?php } ?>
    <br>
    <div>
        <input type="submit" class="button small" value="<?php echo trans('submit'); ?>">
        <a onclick="history.go(-1)">
            <?php echo trans( 'cancel'); ?>
        </a>
    </div>
</form>
