<form action="<?php echo $this->action; ?>" method="post">
    <?php echo csrf_field(); ?>
    <input type="hidden" name="id" value="<?php echo $this->product_purchase->id; ?>">
    <input type="hidden" name="eid" value="<?php echo $this->product->eid; ?>">


    <p><?php echo trans('Are-you-sure-to-delete-this-purchase-url?') ?></p>
    <p><?php echo $this->product_purchase->purchase_url; ?></p>


    <?php if ($this->errors) { ?>
        <p class="errors">
            <?php foreach ($this->errors as $err_key => $err_val) { ?>
                <span class="label alert"><?php echo trans($err_key); ?>, <?php echo trans($err_val); ?></span>
            <?php } ?>
        </p>
    <?php } ?>
    <br>
    <div>
        <input type="submit" class="button small" value="<?php echo trans('submit'); ?>">
        <a href="<?php echo route_url('admin-ui-product-purchase', ['eid' => $this->product->eid]); ?>"><?php echo trans('return'); ?></a>
    </div>
</form>
