<?php
if (!$query = $this->query) {
    $query = http_request()->query->get('query');
}

?><form class="admin-form-query" method="get" action="<?php echo $this->action; ?>">
    <div class="input-group">
        <input class="input-group-field" type="search" name="query" value="<?php echo $query; ?>">
        <input type="hidden" name="t" value="<?php echo $this->t; ?>">
        <div class="input-group-field">
            <button class="button">search</button>
            <?php if ($this->buttons) { ?>
            <?php foreach ($this->buttons as $button) { ?>
            <a href="<?php echo $button['link']; ?>" class="button success"><?php echo $button['text']; ?></a>
            <?php } ?>
            <?php } ?>
        </div>
    </div>
</form>

