<?php $this->layout('layout/user', [
    'html_title' => trans('user-forgot-password'),
]); ?>

<?php $this->section('main'); ?>

<h3 class="retrieve-password-tips"><?php echo trans('fill-in-the-email-you-used-to-register'); ?></h3>

<form class="auth-panel-form w-320" method="post" action="<?php echo route_url('forgot-password-post'); ?>">
    <?php echo csrf_field(); ?>
    <ul class="menu vertical">
        <li>
            <div class="input-field">
                <input type="email" name="email" required="required" placeholder="<?php echo trans('email-address'); ?>"
                       value="<?php echo $this->email; ?>">
            </div>
        </li>
    </ul>
    <?php echo $this->insert('element/errorbox'); ?>
    <div>
        <input type="submit" class="button submit" value="<?php echo trans('submit'); ?>">
    </div>
    <div class="retrieve-password-wrap">
        <a href="<?php echo route_url('mobile-forgot-password') ?>" class="switch-way-to-retrieve">
            <?php echo trans('use-phone-to-retrieve-password'); ?>
        </a>
        <a href="<?php echo route_url('login')?>" class="back-to-login">
            <?php echo trans('back'); ?>
        </a>
    </div>
</form>

<?php $this->replace(); ?>

