<?php $this->layout('layout/user', [
    'html_title' => trans('user-forgot-password'),
]); ?>

<?php $this->section('main'); ?>

<h3 class="retrieve-password-tips"><?php echo trans('fill-in-the-phone-number-you-used-to-register'); ?></h3>

<form class="auth-panel-form w-320" method="post" action="<?php echo route_url('mobile-forgot-password-post'); ?>">
    <?php echo csrf_field(); ?>
    <ul class="menu vertical">
        <li>
            <div class="input-field">
                <input type="number" name="phone_number" required="required" data-type="reged-phone-number"
                       placeholder="<?php echo trans('phone-number'); ?>"
                       value="<?php echo $this->phone_number; ?>">
            </div>
            <p class="phone-error-tips hide error-tips"></p>
        </li>
        <li class="verification-code">
            <div class="input-field">
                <input type="number" name="code" required="required"
                       placeholder="<?php echo trans('verification-code'); ?>" value="<?php echo $this->code; ?>">
            </div>
            <button class="get-retrieve-code get-code">
                <?php echo trans('get-verification-code'); ?>
            </button>
            <p class="sms-error-tips hide error-tips"></p>
        </li>
        <li>
            <div class="input-field">
                <input type="password" name="password" required="required"
                       placeholder="<?php echo trans('new-password'); ?>"
                       value="<?php echo $this->password; ?>">
            </div>
            <i class="icon icon-eye-close view-password"></i>
            <p class="password-error-tips hide error-tips"></p>
        </li>
    </ul>
    <?php echo $this->insert('element/errorbox'); ?>
    <div>
        <input type="submit" class="button submit mobile-retrieve-password-submit"
               value="<?php echo trans('submit'); ?>">
    </div>
    <div class="retrieve-password-wrap">
        <a href="<?php echo route_url('forgot-password') ?>" class="switch-way-to-retrieve">
            <?php echo trans('use-email-to-retrieve-password'); ?>
        </a>
        <a href="<?php echo route_url('login')?>" class="back-to-login">
            <?php echo trans('back'); ?>
        </a>
    </div>
</form>

<?php $this->replace(); ?>

