<?php
$this->layout('layout/user', [
    'html_title' => trans('user-reg'),
    'selected_nav_item' => 'reg'
]);
$errors = $this->errors ? $this->errors : [];
?>

<?php $this->section('main'); ?>

<form method="post" action="<?php echo route_url('mobile-reg-post'); ?>" class="user-form">
    <?php echo csrf_field(); ?>
    <div class="reg-tab">
        <a class="mobile-reg selected" href="<?php echo route_url('mobile-reg'); ?>">
            <i class="icon icon-shouji"></i>
        </a>
        <a class="email-reg" href="<?php echo route_url('reg'); ?>">
            <i class="icon icon-mail"></i>
        </a>
    </div>
    <ul class="menu vertical">
        <li class="item">
            <?php echo $this->insert('element/form/input-field', [
                'type' => 'text',
                'name' => 'nick',
                'placeholder' => trans('nick'),
                'value' => $this->nick,
                'maxlength' => 21,
                'data_type' => '',
                'has_error' => isset($errors['nick'])
            ]); ?>
            <p class="nick-error-tips hide error-tips"></p>
        </li>
        <li class="item phone-number">
            <?php echo $this->insert('element/form/input-field', [
                'type' => 'number',
                'name' => 'phone_number',
                'placeholder' => trans('phone-number'),
                'value' => $this->phone_number,
                'maxlength' => 11,
                'data_type' => 'reg-phone-number',
                'has_error' => isset($errors['phone-number'])
            ]); ?>
            <p class="phone-error-tips hide error-tips"></p>
        </li>
        <li class="item verification-code">
            <?php echo $this->insert('element/form/input-field', [
                'type' => 'number',
                'name' => 'code',
                'placeholder' => trans('verification-code'),
                'value' => $this->code,
                'maxlength' => 6,
                'data_type' => '',
                'has_error' => isset($errors['verification-code'])
            ]); ?>
            <p class="sms-error-tips hide error-tips"></p>

            <button class="get-reg-code get-code">
                <?php echo trans('get-verification-code'); ?>
            </button>
        </li>
        <li class="item">
            <?php echo $this->insert('element/form/input-field', [
                'type' => 'password',
                'name' => 'password',
                'placeholder' => trans('password'),
                'value' => $this->password,
                'maxlength' => 21,
                'data_type' => '',
                'has_error' => isset($errors['password'])
            ]); ?>
            <i class="icon icon-eye-close view-password"></i>
            <p class="password-error-tips hide error-tips"></p>
        </li>

    </ul>

    <?php echo $this->insert('element/errorbox'); ?>

    <div>
        <button class="button submit mobile-reg-submit"><?php echo trans('reg.submit'); ?></button>
    </div>
    <div class="registration-agreement">
        <?php echo trans('click-on-the-register-button-that-is-on-behalf-of-you-agree') ?>
        <a href="<?php echo route_url('ipar-article-show', ['zcode' => '57e497ace5e66']); ?>" target="_blank">
            <?php echo trans('ideapar-registration-agreement') ?>
        </a>
    </div>
</form>

<?php $this->stop(); ?>
