<?php $this->layout('layout/user', [
    'html_title' => trans('user-reset-password'),
]); ?>

<?php $this->section('main'); ?>

    <h3><i class="icon icon-info-success"></i><?php echo trans('reset-password'); ?></h3>

    <form class="auth-panel-form w-320" method="post" action="<?php echo route_url('reset-password-post'); ?>">

        <?php echo csrf_field(); ?>

        <input type="hidden" name="uid" value="<?php echo $this->uid; ?>">
        <input type="hidden" name="token" value="<?php echo $this->token; ?>">
        <input type="hidden" name="date" value="<?php echo $this->date; ?>">
        <input type="hidden" name="encoded_email" value="<?php echo $this->encoded_email; ?>">

        <ul class="menu vertical">
            <li>
                <?php echo $this->insert('element/form/input-field', [
                    'type' => 'text',
                    'name' => 'email',
                    'placeholder' => trans('email'),
                    'value' => $this->email,
                    'data_type' => '',
                    'has_error' => isset($this->errors['email'])
                ]); ?>
            </li>
            <li>
                <div class="input-field">
                    <input type="password" name="password" required="required"
                           placeholder="<?php echo trans('new-password'); ?>" value="">
                </div>
                <i class="icon icon-eye"></i>
            </li>
        </u>
        <?php echo $this->insert('element/errorbox'); ?>
        <div>
            <input type="submit" class="button submit" value="<?php echo trans('submit'); ?>">
        </div>
    </form>

<?php $this->replace(); ?>
