<?php
$article = $this->article;
$items = [
    'content' => [
        'route' => 'admin-article-show',
    ],
    'tag' => [
        'route' => 'admin-ui-article_tag-search',
        'add' => 1,
        'add_route' => 'admin-ui-article_tag-add'
    ],
    'tag-multiple' => [
        'route' => 'admin-ui-tag_article-add_multiple'
    ],
    'comment'=>[
        'route' => 'admin-ui-article_comment-index'
    ]
];
$select = $this->select ? $this->select : 'content';
?>
<div class="entity-menu-rqt">
    <ul class="">
        <?php foreach ($items as $key => $item) { ?>
            <?php
            $route = prop($item, 'route', "admin-article-$key");
            $count = prop($item, 'count', 0);
            $add_route = '';
            if ($add = prop($item, 'add', 0)) {
                $add_route = prop($item, 'add_route', "$route-add");
            }
            ?>
            <li<?php if ($select == $key) echo ' class="selected"'; ?>>
                <a href="<?php echo route_url($route, ['zcode' => $article->zcode]); ?>">
                    <span><?php echo $key; ?></span>
                </a>
                <?php if ($add_route) { ?>
                    <a class="button success" href="<?php echo route_url($add_route, ['zcode' => $article->zcode]); ?>">
                        add
                    </a>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>