<?php
$idea = $this->idea;
if (!$idea) {
    _debug('idea cannot be empty');
}
$items = [
    'story' => [
        'route' => 'admin-idea-show',
        'count' => $idea->countStory(),
    ],
    'content' => [
        'route' => 'admin-idea-content'
    ],
];
$select = $this->select ? $this->select : 'story';
?>
<div class="entity-menu-idea">
    <ul class="">
        <?php foreach ($items as $key => $item) { ?>
<?php
$route = prop($item, 'route', "admin-idea-$key");
$count = prop($item, 'count', 0);
$add_route = '';
if ($add = prop($item, 'add', 0)) {
    $add_route = "$route-add";
}
?>
        <li<?php if ($select == $key) echo ' class="selected"'; ?>>
            <a href="<?php echo route_url($route, ['eid' => $idea->eid]) ; ?>">
                <span><?php echo $key; ?></span>
                <?php if ($count) { ?>(<?php echo $count; ?>)<?php } ?>
            </a>
            <?php if ($add_route) { ?>
            <a class="button success" href="<?php echo route_url($add_route, ['eid' => $idea->eid]); ?>">
                add
            </a>
            <?php } ?>
        </li>
        <?php } ?>
    </ul>
</div>

