<?php $this->layout('layout/admin', [
    'html_title' => trans('admin-ui-group-edit-office'),
    'breadcrumbs' => ['admin-ui-group-index']
]); ?>

<?php $this->section('page-body'); ?>
<div id="page-group-office-edit">
    <div class="row column">
        <h1><?php echo trans('admin-ui-group-office-edit'); ?></h1>
        <?php echo $this->insert('module/form/group_office/admin-form-group_office'); ?>
    </div>

</div>
<?php $this->replace(); ?>
